import "./globals.css";
import SessionProviderWrapper from "@/providers/SessionProviderWrapper";

export const metadata = {
  title: "War Of Devs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='sunset'>
      <body>
        <SessionProviderWrapper>
          {children}
        </SessionProviderWrapper>
        </body>
    </html>
  );
}
